/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT
 * Remora Development | Remora Flow
 * Version: 1.0 | Generated: 2025-11-12
 * 
 * Remora Flow operates under principles of transparency, 
 * fair use, and responsible AI development.
 * 
 * All workflows generated by this software are transformative interpretations created 
 * by analyzing publicly available content such as metadata, transcripts, and structural
 * cues from online videos, articles, or educational media.
 * 
 * This software does not store, reproduce, or distribute any copyrighted visual, audio, 
 * or text-based material. Instead, it extracts semantic patterns and converts them into 
 * new, original workflow structures for educational and productivity purposes.
 * 
 * LEGAL COMPLIANCE:
 * - U.S. Copyright Law (17 U.S.C. §107): Transformative use for commentary, analysis, and education
 * - YouTube Developer Policies (Section 5.B): No redistribution or unauthorized reuse of video content
 * - GDPR (Article 5.1.c): Data minimization, transparency, and user consent for all data processing
 * 
 * ETHICAL STANDARDS:
 * Remora Development ensures that all AI-driven interpretations serve accessibility, 
 * education, and cognitive empowerment. Users retain full control over all inputs, 
 * exports, and deletions of local or cloud-synced data.
 * 
 * © 2025 Remora Development. All rights reserved.
 * Contact: legal@remoradev.ai
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { injectGuardrailNodes, GUARDRAIL_SYSTEM_PROMPT } from "../_shared/guardrails.ts";
import { ROLE_CONTRACT_SYSTEM_PROMPT } from "../_shared/role-contracts.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { description, existingWorkflow } = await req.json();

    if (!description) {
      throw new Error('Description is required');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    // Create abort controller for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 120000); // 2 minute timeout

    console.log('Starting AI request, description length:', description.length);

    const systemPrompt = `You are an AI Workflow Architect.

Goal: Convert the user's description into a workflow graph for a visual editor.

Output requirements:
- Keep the output COMPACT and strictly structured.
- Prefer fewer nodes: target 8–20 nodes, hard cap 25 nodes.
- Node config must be minimal (only essential fields). Avoid large embedded templates.
- Do NOT include large memory blobs unless the user explicitly requests them.
- If the user describes multiple distinct workflows, return them under "workflows".

Schema expectations (high level):
- Either:
  A) { nodes: [...], connections: [...] }
  B) { workflows: [{ name, nodes, connections, context? }...] }
- Optional: context, explanation.

${existingWorkflow ? "If an existingWorkflow is provided, preserve its core intent and reuse node ids where reasonable while improving it." : ""}`;

    const userPrompt = existingWorkflow
      ? `User description:\n${description}\n\nExisting workflow (JSON):\n${JSON.stringify(existingWorkflow)}`
      : `User description:\n${description}`;

    const tools = [
      {
        type: 'function',
        function: {
          name: 'generate_workflow',
          description: 'Generate a workflow graph from a text description.',
          parameters: {
            type: 'object',
            properties: {
              context: { type: 'object', additionalProperties: true },
              workflows: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    name: { type: 'string' },
                    context: { type: 'object', additionalProperties: true },
                    nodes: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          id: { type: 'string' },
                          type: { type: 'string' },
                          title: { type: 'string' },
                          description: { type: 'string' },
                          group: { type: 'string' },
                          priority: { type: 'number' },
                          x: { type: 'number' },
                          y: { type: 'number' },
                          config: { type: 'object', additionalProperties: true },
                        },
                        required: ['id', 'type', 'title', 'x', 'y'],
                        additionalProperties: false,
                      },
                    },
                    connections: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          from: { type: 'string' },
                          to: { type: 'string' },
                        },
                        required: ['from', 'to'],
                        additionalProperties: false,
                      },
                    },
                  },
                  required: ['name', 'nodes', 'connections'],
                  additionalProperties: false,
                },
              },
              nodes: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    id: { type: 'string' },
                    type: { type: 'string' },
                    title: { type: 'string' },
                    description: { type: 'string' },
                    group: { type: 'string' },
                    priority: { type: 'number' },
                    x: { type: 'number' },
                    y: { type: 'number' },
                    config: { type: 'object', additionalProperties: true },
                  },
                  required: ['id', 'type', 'title', 'x', 'y'],
                  additionalProperties: false,
                },
              },
              connections: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    from: { type: 'string' },
                    to: { type: 'string' },
                  },
                  required: ['from', 'to'],
                  additionalProperties: false,
                },
              },
              explanation: { type: 'string' },
            },
            additionalProperties: false,
          },
        },
      },
    ];

    let response;
    try {
      response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${LOVABLE_API_KEY}`,
          'Content-Type': 'application/json',
        },
        signal: controller.signal,
        body: JSON.stringify({
          model: 'google/gemini-2.5-flash',
          max_tokens: 8192,
          temperature: 0.2,
          tools,
          tool_choice: { type: 'function', function: { name: 'generate_workflow' } },
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt },
          ],
        }),
      });
    } catch (fetchError: any) {
      clearTimeout(timeoutId);
      if (fetchError.name === 'AbortError') {
        console.error('Request timed out after 2 minutes');
        return new Response(
          JSON.stringify({ error: 'Request timed out. Try a shorter description or break it into smaller parts.' }),
          { 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 504
          }
        );
      }
      throw fetchError;
    }

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI API error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please wait a moment and try again.' }),
          { 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 429
          }
        );
      }
      
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI credits exhausted. Please add credits in Settings → Workspace → Usage.' }),
          { 
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 402
          }
        );
      }
      
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();

    // Prefer tool-calling output (more reliable than free-form JSON in message.content)
    let parsed: any;
    try {
      const toolArgs = data?.choices?.[0]?.message?.tool_calls?.[0]?.function?.arguments;
      if (typeof toolArgs === 'string' && toolArgs.trim().length > 0) {
        parsed = JSON.parse(toolArgs);
        console.log('Parsed workflow from tool call');
      } else {
        const content = data?.choices?.[0]?.message?.content ?? '';
        let jsonStr = String(content).trim();

        const codeBlockMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
        if (codeBlockMatch) jsonStr = codeBlockMatch[1].trim();

        if (!jsonStr.startsWith('{') && !jsonStr.startsWith('[')) {
          const jsonMatch = jsonStr.match(/(\{[\s\S]*\}|\[[\s\S]*\])/);
          if (jsonMatch) jsonStr = jsonMatch[1];
        }

        parsed = JSON.parse(jsonStr);
        console.log('Parsed workflow from message.content fallback');
      }
    } catch (parseError) {
      console.error('Failed to parse AI response:', parseError);
      throw new Error('AI returned an unreadable response. Please try again with a shorter prompt or fewer requirements.');
    }

    // Automatically inject guardrail nodes and role contracts
    if (parsed.workflows && Array.isArray(parsed.workflows)) {
      // Multiple workflows detected
      for (const workflow of parsed.workflows) {
        if (workflow.nodes) {
          const injectionResult = injectGuardrailNodes(workflow.nodes);
          workflow.nodes = injectionResult.nodes;
          workflow.guardrailExplanations = injectionResult.explanations;
          workflow.complianceStandards = injectionResult.complianceStandards;
          workflow.guardrailsAdded = injectionResult.guardrailsAdded;
          workflow.riskScore = injectionResult.riskScore;
          workflow.roleAssignments = injectionResult.roleAssignments;
          workflow.roleViolations = injectionResult.roleViolations;
          workflow.roleContractExplanation = injectionResult.roleContractExplanation;
        }
      }
      console.log('Multiple workflows detected:', parsed.workflows.length);
    } else if (parsed.nodes) {
      // Single workflow
      const injectionResult = injectGuardrailNodes(parsed.nodes);
      parsed.nodes = injectionResult.nodes;
      parsed.guardrailExplanations = injectionResult.explanations;
      parsed.complianceStandards = injectionResult.complianceStandards;
      parsed.guardrailsAdded = injectionResult.guardrailsAdded;
      parsed.riskScore = injectionResult.riskScore;
      parsed.roleAssignments = injectionResult.roleAssignments;
      parsed.roleViolations = injectionResult.roleViolations;
      parsed.roleContractExplanation = injectionResult.roleContractExplanation;
      console.log('Guardrail nodes injected:', injectionResult.guardrailsAdded);
      console.log('Compliance standards detected:', injectionResult.complianceStandards);
      console.log('Role assignments:', injectionResult.roleAssignments?.length || 0);
      if (injectionResult.roleViolations?.length) {
        console.warn('Role violations blocked:', injectionResult.roleViolations.length);
      }
    }

    console.log('Generated workflow:', parsed);

    return new Response(
      JSON.stringify(parsed),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error in generate-workflow-from-text:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500
      }
    );
  }
});