/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT
 * Remora Development | Remora Flow
 * Version: 1.0 | Generated: 2025-11-12
 * 
 * Remora Flow operates under principles of transparency, 
 * fair use, and responsible AI development.
 * 
 * All workflows generated by this software are transformative interpretations created 
 * by analyzing publicly available content such as metadata, transcripts, and structural
 * cues from online videos, articles, or educational media.
 * 
 * This software does not store, reproduce, or distribute any copyrighted visual, audio, 
 * or text-based material. Instead, it extracts semantic patterns and converts them into 
 * new, original workflow structures for educational and productivity purposes.
 * 
 * LEGAL COMPLIANCE:
 * - U.S. Copyright Law (17 U.S.C. §107): Transformative use for commentary, analysis, and education
 * - GDPR (Article 5.1.c): Data minimization, transparency, and user consent for all data processing
 * 
 * ETHICAL STANDARDS:
 * Remora Development ensures that all AI-driven interpretations serve accessibility, 
 * education, and cognitive empowerment. Users retain full control over all inputs, 
 * exports, and deletions of local or cloud-synced data.
 * 
 * © 2025 Remora Development. All rights reserved.
 * Contact: legal@remoradev.ai
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { injectGuardrailNodes, GUARDRAIL_SYSTEM_PROMPT } from "../_shared/guardrails.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { videoData, fileName, existingWorkflow } = await req.json();
    
    console.log('Analyzing uploaded video file:', fileName);

    if (!videoData) {
      throw new Error('No video data provided');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    // Extract video context
    const videoContext = {
      fileName,
      fileType: fileName.split('.').pop(),
      uploadedAt: new Date().toISOString(),
      source: 'uploaded_file',
    };

    const systemPrompt = `You are an Expert Workflow Architect analyzing video content to extract automation workflows, processes, and complete decision architectures.

${GUARDRAIL_SYSTEM_PROMPT}

CRITICAL INSTRUCTIONS:
1. Extract COMPLETE workflow architecture from video analysis including:
   - All sequential steps showing the full process flow
   - Decision points with ALL branches (if/else, switch cases, multiple paths)
   - Parallel operations and async workflows
   - Loop structures and iteration patterns
   - Error handling nodes and fallback scenarios
   - Validation and guardrail checkpoints

2. For each decision point, create branching nodes:
   - Condition being evaluated
   - TRUE path with subsequent actions
   - FALSE path with alternative flow
   - Edge cases and error states

3. Identify workflow patterns from video:
   - Tutorial steps → Sequential action nodes
   - Demonstrations → Step-by-step workflow
   - Comparisons → Conditional branches
   - Tips/best practices → Optimization nodes
   - Common mistakes → Error handling

4. Include AI-optimized patterns:
   - Async operations opportunities
   - Caching and performance optimization points
   - Rate limiting requirements
   - Data transformation pipelines

Return complete workflow JSON with nodes array showing FULL decision tree and all branches.`;

    const prompt = existingWorkflow 
      ? `Enhance this workflow with insights from the uploaded video.\n\nVideo: ${fileName}\nContext: ${JSON.stringify(videoContext)}\n\nExisting Workflow: ${JSON.stringify(existingWorkflow)}\n\nAdd missing decision branches, optimizations, and error handling.`
      : `Analyze this video and extract a COMPLETE workflow architecture with all decision points and branches.\n\nVideo: ${fileName}\nContext: ${JSON.stringify(videoContext)}\n\nNote: This is a video file upload. Analyze the structure, patterns, and processes demonstrated in the video to create a comprehensive workflow with complete decision trees.`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { 
            role: 'user', 
            content: [
              { type: 'text', text: prompt },
              { 
                type: 'image_url', 
                image_url: { 
                  url: videoData // Can be video thumbnail or base64 image from video frame
                } 
              }
            ]
          }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI API error:', response.status, errorText);
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices[0].message.content;

    let parsedResult;
    try {
      const jsonMatch = content.match(/```json\n([\s\S]*?)\n```/) || content.match(/```\n([\s\S]*?)\n```/);
      const jsonString = jsonMatch ? jsonMatch[1] : content;
      parsedResult = JSON.parse(jsonString);

      // Inject guardrails
      if (parsedResult.nodes) {
        const injectionResult = injectGuardrailNodes(parsedResult.nodes);
        parsedResult.nodes = injectionResult.nodes;
        parsedResult.guardrailExplanations = injectionResult.explanations;
        parsedResult.complianceStandards = injectionResult.complianceStandards;
        parsedResult.guardrailsAdded = injectionResult.guardrailsAdded;
        console.log('Guardrails injected:', injectionResult.guardrailsAdded);
      }

      // Add video context
      parsedResult.context = {
        ...parsedResult.context,
        ...videoContext,
      };

    } catch (error) {
      console.error('Failed to parse AI response:', error);
      parsedResult = {
        nodes: [],
        insights: content,
        explanation: 'Failed to parse structured workflow data',
        context: videoContext,
      };
    }

    return new Response(
      JSON.stringify(parsedResult),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200
      }
    );

  } catch (error) {
    console.error('Error analyzing video file:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error analyzing video file' 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
