/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT
 * Remora Development | Remora Flow
 * Version: 1.0 | Generated: 2025-11-12
 * 
 * Remora Flow operates under principles of transparency, 
 * fair use, and responsible AI development.
 * 
 * All workflows generated by this software are transformative interpretations created 
 * by analyzing publicly available content such as metadata, transcripts, and structural
 * cues from online videos, articles, or educational media.
 * 
 * This software does not store, reproduce, or distribute any copyrighted visual, audio, 
 * or text-based material. Instead, it extracts semantic patterns and converts them into 
 * new, original workflow structures for educational and productivity purposes.
 * 
 * LEGAL COMPLIANCE:
 * - U.S. Copyright Law (17 U.S.C. §107): Transformative use for commentary, analysis, and education
 * - TikTok Developer Policies: No redistribution or unauthorized reuse of video content
 * - GDPR (Article 5.1.c): Data minimization, transparency, and user consent for all data processing
 * 
 * ETHICAL STANDARDS:
 * Remora Development ensures that all AI-driven interpretations serve accessibility, 
 * education, and cognitive empowerment. Users retain full control over all inputs, 
 * exports, and deletions of local or cloud-synced data.
 * 
 * © 2025 Remora Development. All rights reserved.
 * Contact: legal@remoradev.ai
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { injectGuardrailNodes, GUARDRAIL_SYSTEM_PROMPT } from "../_shared/guardrails.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Extract TikTok video ID from URL
function extractTikTokId(url: string): string | null {
  const patterns = [
    /tiktok\.com\/@[\w.-]+\/video\/(\d+)/,
    /vm\.tiktok\.com\/(\w+)/,
    /vt\.tiktok\.com\/(\w+)/,
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { videoUrl, existingWorkflow } = await req.json();
    
    console.log('Analyzing TikTok video:', videoUrl);

    const videoId = extractTikTokId(videoUrl);
    if (!videoId) {
      throw new Error('Invalid TikTok URL format');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    // Extract video context from URL and structure
    const videoContext = {
      videoId,
      url: videoUrl,
      platform: 'TikTok',
      timestamp: new Date().toISOString(),
    };

    const systemPrompt = `You are an Expert Workflow Architect analyzing TikTok content to extract automation workflows, processes, and decision trees.

${GUARDRAIL_SYSTEM_PROMPT}

CRITICAL INSTRUCTIONS:
1. Extract COMPLETE workflow architecture including:
   - All sequential steps and parallel branches
   - Decision points with ALL possible paths (if/else, switch cases)
   - Loop structures and iteration logic
   - Error handling and fallback scenarios
   - Validation checkpoints

2. For each decision point, create condition nodes that show:
   - The condition being evaluated
   - TRUE path leading to one set of actions
   - FALSE path leading to alternative actions
   - Edge cases and error states

3. Identify AI-optimized best practices:
   - Async operations and parallel processing opportunities
   - Caching and optimization points
   - Rate limiting and throttling needs
   - Data transformation pipelines

4. Map TikTok content to workflow structure:
   - Tutorial steps → Sequential action nodes
   - Decision points in content → Condition nodes with branches
   - Tips/tricks → Optimization nodes
   - Common mistakes → Error handling nodes

Return structured JSON with nodes array and connections showing the FULL decision tree.`;

    const prompt = existingWorkflow 
      ? `Enhance this workflow with insights from TikTok video.\n\nVideo: ${videoUrl}\nContext: ${JSON.stringify(videoContext)}\n\nExisting Workflow: ${JSON.stringify(existingWorkflow)}\n\nAdd missing decision branches, error handling, and optimizations.`
      : `Analyze this TikTok video and extract a COMPLETE workflow with all decision points, branches, and best practices.\n\nVideo: ${videoUrl}\nContext: ${JSON.stringify(videoContext)}\n\nReturn COMPLETE workflow architecture including all conditional branches.`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI API error:', response.status, errorText);
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices[0].message.content;

    let parsedResult;
    try {
      const jsonMatch = content.match(/```json\n([\s\S]*?)\n```/) || content.match(/```\n([\s\S]*?)\n```/);
      const jsonString = jsonMatch ? jsonMatch[1] : content;
      parsedResult = JSON.parse(jsonString);

      // Inject guardrails
      if (parsedResult.nodes) {
        const injectionResult = injectGuardrailNodes(parsedResult.nodes);
        parsedResult.nodes = injectionResult.nodes;
        parsedResult.guardrailExplanations = injectionResult.explanations;
        parsedResult.complianceStandards = injectionResult.complianceStandards;
        parsedResult.guardrailsAdded = injectionResult.guardrailsAdded;
        console.log('Guardrails injected:', injectionResult.guardrailsAdded);
      }

      // Add video context
      parsedResult.context = {
        ...parsedResult.context,
        ...videoContext,
      };

    } catch (error) {
      console.error('Failed to parse AI response:', error);
      parsedResult = {
        nodes: [],
        insights: content,
        explanation: 'Failed to parse structured workflow data',
        context: videoContext,
      };
    }

    return new Response(
      JSON.stringify(parsedResult),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200
      }
    );

  } catch (error) {
    console.error('Error analyzing TikTok video:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error analyzing TikTok video' 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
