import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Shield, Scale, Lock, FileCheck, AlertCircle, CheckCircle } from "lucide-react";

export default function Legal() {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <main className="flex-1 overflow-auto">
          <div className="container mx-auto py-8 px-4 max-w-5xl">
            <div className="mb-8">
              <div className="flex items-center gap-3 mb-4">
                <Shield className="w-10 h-10 text-primary" />
                <div>
                  <h1 className="text-4xl font-bold">AI Transparency & Fair-Use Statement</h1>
                  <p className="text-muted-foreground mt-2">
                    Remora Development | FlowMind & Shadow IDE
                  </p>
                </div>
              </div>
              <div className="flex gap-4 text-sm text-muted-foreground">
                <span>Version: 1.0</span>
                <span>•</span>
                <span>Generated: 2025-11-12</span>
                <span>•</span>
                <span>Contact: legal@remoradev.ai</span>
              </div>
            </div>

            <ScrollArea className="h-[calc(100vh-250px)]">
              <div className="space-y-6 pr-4">
                {/* Overview */}
                <Card>
                  <CardHeader>
                    <CardTitle>Overview</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <p>
                      FlowMind and its associated applications operate under principles of{" "}
                      <strong>transparency, fair use, and responsible AI development</strong>.
                    </p>
                    <p>
                      All workflows generated by this software are <strong>transformative interpretations</strong>{" "}
                      created by analyzing publicly available content such as metadata, transcripts, and structural{" "}
                      cues from online videos, articles, or educational media.
                    </p>
                    <p>
                      This software <strong>does not store, reproduce, or distribute</strong> any copyrighted visual,{" "}
                      audio, or text-based material. Instead, it extracts semantic patterns and converts them into{" "}
                      new, original workflow structures for educational and productivity purposes.
                    </p>
                  </CardContent>
                </Card>

                {/* Legal Compliance */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <Scale className="w-5 h-5 text-primary" />
                      <CardTitle>Legal Compliance</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div>
                      <h3 className="font-semibold mb-2">U.S. Copyright Law (17 U.S.C. §107)</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        This software operates under the <strong>Fair Use</strong> doctrine for transformative works:
                      </p>
                      <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                        <li><strong>Purpose:</strong> Commentary, analysis, criticism, education, and research</li>
                        <li><strong>Nature:</strong> Transformation of publicly available metadata into original workflow structures</li>
                        <li><strong>Amount:</strong> Minimal use of source material (metadata and structural cues only)</li>
                        <li><strong>Market Effect:</strong> No negative impact on the market for the original work</li>
                      </ul>
                    </div>

                    <div>
                      <h3 className="font-semibold mb-2">YouTube Developer Policies (Section 5.B)</h3>
                      <p className="text-sm text-muted-foreground mb-2">Compliant with YouTube's terms regarding:</p>
                      <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                        <li>No unauthorized redistribution or reuse of video content</li>
                        <li>No storage of copyrighted audio or visual material</li>
                        <li>Metadata analysis only (titles, descriptions, captions, timing structures)</li>
                      </ul>
                    </div>

                    <div>
                      <h3 className="font-semibold mb-2">GDPR (Article 5.1.c) - Data Minimization</h3>
                      <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                        <li>Transparency in all data processing activities</li>
                        <li>User consent for all data collection and usage</li>
                        <li>Minimal data retention policies</li>
                        <li>Full user control over data inputs, exports, and deletions</li>
                      </ul>
                    </div>
                  </CardContent>
                </Card>

                {/* Ethical Standards */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <Lock className="w-5 h-5 text-primary" />
                      <CardTitle>Ethical Standards</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <p className="text-sm text-muted-foreground">
                      Remora Development ensures that all AI-driven interpretations serve:
                    </p>
                    <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                      <li><strong>Accessibility:</strong> Making complex information structures more understandable</li>
                      <li><strong>Education:</strong> Supporting learning and knowledge synthesis</li>
                      <li><strong>Cognitive Empowerment:</strong> Enhancing human productivity and creativity</li>
                    </ul>
                    
                    <div className="border-t pt-4">
                      <h3 className="font-semibold mb-2">User Rights</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        Users retain <strong>full control</strong> over:
                      </p>
                      <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                        <li>All input data and content</li>
                        <li>Generated workflow exports</li>
                        <li>Local and cloud-synced data</li>
                        <li>Deletion and privacy settings</li>
                      </ul>
                    </div>
                  </CardContent>
                </Card>

                {/* What This Software Does NOT Do */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <AlertCircle className="w-5 h-5 text-destructive" />
                      <CardTitle>What This Software Does NOT Do</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2 text-sm text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <span className="text-destructive mt-0.5">❌</span>
                        <span>Download or store copyrighted video, audio, or visual content</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-destructive mt-0.5">❌</span>
                        <span>Redistribute or monetize original creator content</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-destructive mt-0.5">❌</span>
                        <span>Bypass platform restrictions or terms of service</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-destructive mt-0.5">❌</span>
                        <span>Violate intellectual property rights</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-destructive mt-0.5">❌</span>
                        <span>Process data without user consent or transparency</span>
                      </li>
                    </ul>
                  </CardContent>
                </Card>

                {/* What This Software DOES Do */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <CheckCircle className="w-5 h-5 text-primary" />
                      <CardTitle>What This Software DOES Do</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2 text-sm text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Analyze publicly accessible metadata (titles, descriptions, transcripts)</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Extract semantic patterns and structural information</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Generate transformative, original workflow interpretations</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Serve educational and productivity purposes</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Comply with U.S. and international copyright laws</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-0.5">✅</span>
                        <span>Provide transparency in all AI operations</span>
                      </li>
                    </ul>
                  </CardContent>
                </Card>

                {/* Jurisdictional Compliance */}
                <Card>
                  <CardHeader>
                    <div className="flex items-center gap-2">
                      <FileCheck className="w-5 h-5 text-primary" />
                      <CardTitle>Jurisdictional Compliance</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-3">
                      This software is designed to comply with laws in:
                    </p>
                    <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                      <li><strong>United States:</strong> Fair Use doctrine (17 U.S.C. §107)</li>
                      <li><strong>European Union:</strong> GDPR (Regulation 2016/679)</li>
                      <li><strong>International:</strong> Berne Convention principles</li>
                    </ul>
                  </CardContent>
                </Card>

                {/* Contact */}
                <Card>
                  <CardHeader>
                    <CardTitle>Contact & Legal Inquiries</CardTitle>
                    <CardDescription>
                      For legal questions, compliance concerns, or rights-related inquiries
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-1 text-sm">
                      <p><strong>Remora Development LLC</strong></p>
                      <p>Email: <a href="mailto:legal@remoradev.ai" className="text-primary hover:underline">legal@remoradev.ai</a></p>
                      <p>Website: <a href="https://remoradev.ai" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">https://remoradev.ai</a></p>
                    </div>
                  </CardContent>
                </Card>

                {/* User Responsibility */}
                <Card className="border-amber-500/50 bg-amber-500/5">
                  <CardHeader>
                    <CardTitle className="text-amber-600 dark:text-amber-400">User Responsibility</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      While this software is designed to comply with applicable laws and platform policies,{" "}
                      <strong>users are ultimately responsible</strong> for:
                    </p>
                    <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground mt-3">
                      <li>Ensuring their own use complies with local laws</li>
                      <li>Respecting intellectual property rights</li>
                      <li>Following platform-specific terms of service</li>
                      <li>Using generated workflows ethically and legally</li>
                    </ul>
                  </CardContent>
                </Card>

                {/* Footer */}
                <div className="text-center py-6 text-sm text-muted-foreground border-t">
                  <p className="font-medium">© 2025 Remora Development. All rights reserved.</p>
                  <p className="mt-2 text-xs">
                    This document may be referenced, cited, or shared for legal compliance purposes.
                    Any modifications to this software's behavior that affect legal compliance will result
                    in an updated version of this statement.
                  </p>
                </div>
              </div>
            </ScrollArea>
          </div>
        </main>
      </div>
    </SidebarProvider>
  );
}
