/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT COMPONENT
 * Displays comprehensive legal compliance and ethical standards for Shadow IDE and FlowMind
 * Version: 1.0 | Remora Development
 */

export const LegalFooter = () => {
  return (
    <footer className="border-t border-border/40 bg-background/50 backdrop-blur-sm py-8 mt-auto">
      <div className="container mx-auto px-4">
        <div className="text-center text-sm text-muted-foreground space-y-4">
          <div>
            <h3 className="font-semibold text-foreground mb-2">
              AI Transparency & Fair-Use Statement
            </h3>
            <p className="text-xs">
              FlowMind & Shadow IDE | Remora Development LLC
            </p>
          </div>
          
          <div className="max-w-3xl mx-auto space-y-3">
            <p>
              FlowMind and its associated applications operate under principles of <strong>transparency, fair use, and responsible AI development</strong>.
            </p>
            <p>
              All workflows generated by this software are <strong>transformative interpretations</strong> created by analyzing publicly available content such as metadata, transcripts, and structural cues from online videos, articles, or educational media.
            </p>
            <p>
              This software <strong>does not store, reproduce, or distribute</strong> any copyrighted visual, audio, or text-based material. Instead, it extracts semantic patterns and converts them into new, original workflow structures for educational and productivity purposes.
            </p>
          </div>

          <div className="border-t border-border/40 pt-4 max-w-2xl mx-auto">
            <p className="font-medium text-foreground mb-2">⚖️ Legal Compliance</p>
            <ul className="text-xs space-y-1">
              <li><strong>U.S. Copyright Law (17 U.S.C. §107)</strong>: Transformative use for commentary, analysis, and education</li>
              <li><strong>YouTube Developer Policies (Section 5.B)</strong>: No redistribution or unauthorized reuse of video content</li>
              <li><strong>GDPR (Article 5.1.c)</strong>: Data minimization, transparency, and user consent for all data processing</li>
            </ul>
          </div>

          <div className="border-t border-border/40 pt-4 max-w-2xl mx-auto">
            <p className="font-medium text-foreground mb-2">🔐 Ethical Standards</p>
            <p className="text-xs">
              Remora Development ensures that all AI-driven interpretations serve accessibility, education, and cognitive empowerment. 
              Users retain full control over all inputs, exports, and deletions of local or cloud-synced data.
            </p>
          </div>

          <div className="border-t border-border/40 pt-4">
            <p className="text-xs">
              © 2025 Remora Development. All rights reserved.
            </p>
            <p className="text-xs mt-1">
              Contact: legal@remoradev.ai | Version: 1.0
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};
