/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT
 * Remora Development | FlowMind & Shadow IDE
 * Version: 1.0 | Generated: 2025-11-12
 * 
 * FlowMind and its associated applications operate under principles of transparency, 
 * fair use, and responsible AI development.
 * 
 * All workflows generated by this software are transformative interpretations created 
 * by analyzing publicly available content such as metadata, transcripts, and structural 
 * cues from online videos, articles, or educational media.
 * 
 * This software does not store, reproduce, or distribute any copyrighted visual, audio, 
 * or text-based material. Instead, it extracts semantic patterns and converts them into 
 * new, original workflow structures for educational and productivity purposes.
 * 
 * LEGAL COMPLIANCE:
 * - U.S. Copyright Law (17 U.S.C. §107): Transformative use for commentary, analysis, and education
 * - YouTube Developer Policies (Section 5.B): No redistribution or unauthorized reuse of video content
 * - GDPR (Article 5.1.c): Data minimization, transparency, and user consent for all data processing
 * 
 * ETHICAL STANDARDS:
 * Remora Development ensures that all AI-driven interpretations serve accessibility, 
 * education, and cognitive empowerment. Users retain full control over all inputs, 
 * exports, and deletions of local or cloud-synced data.
 * 
 * © 2025 Remora Development. All rights reserved.
 * Contact: legal@remoradev.ai
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Extract video ID from various YouTube URL formats
function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

// Fetch video transcript using YouTube's timedtext API
async function fetchTranscript(videoId: string): Promise<string> {
  try {
    // First, get the video page to extract caption tracks
    const videoPageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
    const videoPageText = await videoPageResponse.text();
    
    // Look for caption track URL in the page
    const captionMatch = videoPageText.match(/"captionTracks":\s*(\[.*?\])/);
    if (!captionMatch) {
      console.log('No captions found for video');
      return '';
    }
    
    const captionTracks = JSON.parse(captionMatch[1]);
    if (captionTracks.length === 0) return '';
    
    // Get the first English caption track or any available track
    const englishTrack = captionTracks.find((t: any) => t.languageCode === 'en') || captionTracks[0];
    const captionUrl = englishTrack.baseUrl;
    
    // Fetch the actual captions
    const captionResponse = await fetch(captionUrl);
    const captionXml = await captionResponse.text();
    
    // Parse XML and extract text
    const textMatches = captionXml.matchAll(/<text[^>]*>(.*?)<\/text>/g);
    const transcript = Array.from(textMatches)
      .map(match => match[1]
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
      )
      .join(' ');
    
    return transcript;
  } catch (error) {
    console.error('Error fetching transcript:', error);
    return '';
  }
}

// Fetch video metadata using oEmbed API (no API key required)
async function fetchMetadata(videoId: string) {
  try {
    const response = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
    if (!response.ok) throw new Error('Failed to fetch metadata');
    return await response.json();
  } catch (error) {
    console.error('Error fetching metadata:', error);
    return null;
  }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { url } = await req.json();

    if (!url) {
      throw new Error('YouTube URL is required');
    }

    console.log('Processing YouTube URL:', url);
    const videoId = extractVideoId(url);
    
    if (!videoId) {
      throw new Error('Invalid YouTube URL');
    }

    console.log('Extracted video ID:', videoId);

    // Fetch video data in parallel
    const [transcript, metadata] = await Promise.all([
      fetchTranscript(videoId),
      fetchMetadata(videoId)
    ]);

    console.log('Metadata:', metadata);
    console.log('Transcript length:', transcript.length);

    if (!transcript && !metadata) {
      throw new Error('Could not extract any data from the video');
    }

    // Construct a comprehensive description for workflow generation
    const videoDescription = `
YouTube Video Analysis:
Title: ${metadata?.title || 'Unknown'}
Author: ${metadata?.author_name || 'Unknown'}

${transcript ? `Video Content/Transcript:\n${transcript.slice(0, 4000)}${transcript.length > 4000 ? '...' : ''}` : 'No transcript available'}

${metadata?.description || ''}
    `.trim();

    return new Response(
      JSON.stringify({
        videoId,
        title: metadata?.title,
        author: metadata?.author_name,
        thumbnail: metadata?.thumbnail_url,
        transcript: transcript || null,
        description: videoDescription,
        transcriptLength: transcript.length,
        hasTranscript: !!transcript
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200
      }
    );

  } catch (error: any) {
    console.error('Error in analyze-youtube-video:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400
      }
    );
  }
});
