/**
 * AI TRANSPARENCY & FAIR-USE STATEMENT
 * Remora Development | Remora Flow
 * Version: 1.0 | Generated: 2025-11-12
 * 
 * Remora Flow operates under principles of transparency, 
 * fair use, and responsible AI development.
 * 
 * All workflows generated by this software are transformative interpretations created 
 * by analyzing publicly available content such as metadata, transcripts, and structural
 * cues from online videos, articles, or educational media.
 * 
 * This software does not store, reproduce, or distribute any copyrighted visual, audio, 
 * or text-based material. Instead, it extracts semantic patterns and converts them into 
 * new, original workflow structures for educational and productivity purposes.
 * 
 * LEGAL COMPLIANCE:
 * - U.S. Copyright Law (17 U.S.C. §107): Transformative use for commentary, analysis, and education
 * - YouTube Developer Policies (Section 5.B): No redistribution or unauthorized reuse of video content
 * - GDPR (Article 5.1.c): Data minimization, transparency, and user consent for all data processing
 * 
 * ETHICAL STANDARDS:
 * Remora Development ensures that all AI-driven interpretations serve accessibility, 
 * education, and cognitive empowerment. Users retain full control over all inputs, 
 * exports, and deletions of local or cloud-synced data.
 * 
 * © 2025 Remora Development. All rights reserved.
 * Contact: legal@remoradev.ai
 */

import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';
import { injectGuardrailNodes, GUARDRAIL_SYSTEM_PROMPT } from "../_shared/guardrails.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const MAX_IMAGE_SIZE = 10 * 1024 * 1024; // 10MB

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Received image analysis request');
    
    const { images, image, existingWorkflow } = await req.json();
    
    // Support both single image (legacy) and multiple images
    const imageArray = images || (image ? [image] : []);
    
    // Input validation
    if (!imageArray || imageArray.length === 0) {
      return new Response(
        JSON.stringify({ error: 'No images provided' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!Array.isArray(imageArray)) {
      return new Response(
        JSON.stringify({ error: 'Images must be an array' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (imageArray.length > 5) {
      return new Response(
        JSON.stringify({ error: 'Maximum 5 images allowed per request' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate each image
    for (let i = 0; i < imageArray.length; i++) {
      const img = imageArray[i];
      
      if (typeof img !== 'string') {
        return new Response(
          JSON.stringify({ error: `Image ${i + 1} must be a string (base64 or URL)` }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      // Check image size for base64 images
      if (img.startsWith('data:')) {
        const base64Data = img.split(',')[1];
        const sizeInBytes = (base64Data.length * 3) / 4;
        if (sizeInBytes > MAX_IMAGE_SIZE) {
          return new Response(
            JSON.stringify({ error: `Image ${i + 1} exceeds maximum size of ${MAX_IMAGE_SIZE / 1024 / 1024}MB` }),
            { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
          );
        }
      }
    }

    console.log(`Analyzing ${imageArray.length} workflow image(s)...`);

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Create AbortController for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 115000); // 115s (functions have 2-min limit)

    try {
      // Build the content array with all images
      const userContent: any[] = [
        {
          type: 'text',
          text: imageArray.length > 1
            ? `Extract a single cohesive workflow from these ${imageArray.length} images. Call extract_workflow with every node and connection visible.`
            : 'Extract the workflow from this image. Call extract_workflow with every node and connection visible.'
        }
      ];

      imageArray.forEach((img: string) => {
        userContent.push({
          type: 'image_url',
          image_url: { url: img }
        });
      });

      // Tool-calling schema — forces compact, valid JSON and avoids truncation on large whiteboards
      const extractWorkflowTool = {
        type: 'function',
        function: {
          name: 'extract_workflow',
          description: 'Return the workflow extracted from the image(s)',
          parameters: {
            type: 'object',
            properties: {
              nodes: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    id: { type: 'string' },
                    type: { type: 'string', enum: ['trigger', 'action', 'condition', 'data', 'ai', 'connector'] },
                    title: { type: 'string' },
                    description: { type: 'string' },
                    x: { type: 'number' },
                    y: { type: 'number' },
                    next: { type: 'array', items: { type: 'string' }, description: 'IDs of downstream nodes (success/YES path)' },
                    nextOnFalse: { type: 'array', items: { type: 'string' }, description: 'IDs of NO/false branch (decisions only)' },
                    config: { type: 'object', additionalProperties: true }
                  },
                  required: ['id', 'type', 'title']
                }
              },
              insights: { type: 'string' }
            },
            required: ['nodes']
          }
        }
      };

      // Gemini 3 Flash Preview — much faster than 2.5-flash for vision + structured extraction
      const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${LOVABLE_API_KEY}`,
          'Content-Type': 'application/json',
        },
        signal: controller.signal,
        body: JSON.stringify({
          model: 'google/gemini-3-flash-preview',
          tools: [extractWorkflowTool],
          tool_choice: { type: 'function', function: { name: 'extract_workflow' } },
          messages: [
            {
              role: 'system',
              content: `You convert workflow diagrams/whiteboards into structured workflow JSON via the extract_workflow tool.

${GUARDRAIL_SYSTEM_PROMPT}

${existingWorkflow ? `IMPROVING existing workflow — preserve existing node IDs where unchanged, add new IDs for new nodes:\n${JSON.stringify(existingWorkflow).slice(0, 4000)}\n` : ''}

RULES:
- Extract EVERY node visible (boxes, diamonds, cylinders). Decisions/diamonds = "condition". Triggers/inputs = "trigger". Manual tasks & system processes = "action". External systems/DBs = "connector". AI steps = "ai". Data ops = "data".
- For each node populate "next" with downstream IDs following SOLID lines (success/YES). For condition nodes also populate "nextOnFalse" for the NO/dashed branch.
- Position x/y on a grid by the visible layout: x = column*280, y = row*160.
- Put any visible config (URLs, methods, schedules, recipients, queries, auth) into config. Use {{context.field}} for secrets.
- Use concise titles (1-5 words) and one-line descriptions.
- Call the tool exactly once with ALL nodes. Do NOT reply with text.`
            },
            {
              role: 'user',
              content: userContent
            }
          ],
          temperature: 0.2
        }),
      });

    clearTimeout(timeoutId);

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again in a moment.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI credits exhausted. Please add credits to continue.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      const errorText = await response.text();
      console.error('AI Gateway error:', response.status, errorText);
      throw new Error(`AI Gateway error: ${response.status}`);
    }

    const data = await response.json();
    const message = data.choices?.[0]?.message;
    const toolCall = message?.tool_calls?.[0];
    const rawArgs = toolCall?.function?.arguments ?? message?.content;

    if (!rawArgs) {
      throw new Error('No response from AI');
    }

    // Parse tool-call arguments (usually a JSON string)
    let workflowData;
    try {
      if (typeof rawArgs === 'object') {
        workflowData = rawArgs;
      } else {
        let jsonStr = rawArgs.trim();
        const codeBlockMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
        if (codeBlockMatch) jsonStr = codeBlockMatch[1].trim();
        if (!jsonStr.startsWith('{') && !jsonStr.startsWith('[')) {
          const jsonMatch = jsonStr.match(/(\{[\s\S]*\}|\[[\s\S]*\])/);
          if (jsonMatch) jsonStr = jsonMatch[1];
        }
        workflowData = JSON.parse(jsonStr);
      }
      console.log(`Parsed workflow — ${workflowData.nodes?.length ?? 0} nodes`);
      
      // If AI returned multiple workflows in a workflows array, validate each has nodes
      if (workflowData.workflows && Array.isArray(workflowData.workflows)) {
        console.log(`Detected ${workflowData.workflows.length} workflows from AI response`);
        workflowData.workflows = workflowData.workflows.map((workflow: any, index: number) => {
          if (!workflow.nodes || !Array.isArray(workflow.nodes)) {
            console.warn(`Workflow ${index} missing nodes array, attempting to fix`);
            // If workflow has no nodes but has other data, try to extract nodes
            workflow.nodes = [];
          }
          
          // Inject guardrails for each workflow
          if (workflow.nodes.length > 0) {
            const injectionResult = injectGuardrailNodes(workflow.nodes);
            workflow.nodes = injectionResult.nodes;
            workflow.guardrailExplanations = injectionResult.explanations;
            workflow.complianceStandards = injectionResult.complianceStandards;
            workflow.guardrailsAdded = injectionResult.guardrailsAdded;
            workflow.model = 'google/gemini-2.5-flash';
            workflow.inputType = 'image';
            workflow.insights = workflow.insights || workflow.explanation || `AI vision interpreted ${imageArray.length} source image(s) and converted the visible whiteboard/process structure into workflow nodes, connections, and implementation notes.`;
            console.log(`Guardrails injected for workflow ${index}:`, injectionResult.guardrailsAdded);
          }
          
          return workflow;
        });
      } else {
        // Single workflow - inject guardrails
        if (workflowData.nodes) {
          const injectionResult = injectGuardrailNodes(workflowData.nodes);
          workflowData.nodes = injectionResult.nodes;
          workflowData.guardrailExplanations = injectionResult.explanations;
          workflowData.complianceStandards = injectionResult.complianceStandards;
          workflowData.guardrailsAdded = injectionResult.guardrailsAdded;
          workflowData.model = 'google/gemini-2.5-flash';
          workflowData.inputType = 'image';
          workflowData.insights = workflowData.insights || workflowData.explanation || `AI vision interpreted ${imageArray.length} source image(s) and converted the visible whiteboard/process structure into workflow nodes, connections, and implementation notes.`;
          console.log('Guardrail nodes injected from image analysis:', injectionResult.guardrailsAdded);
        }
      }
    } catch (parseError) {
      console.error('Failed to parse AI response as JSON:', parseError);
      console.error('Content preview:', content.substring(0, 500));
      throw new Error('AI returned invalid JSON format. Please try again.');
    }

    return new Response(
      JSON.stringify(workflowData),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

    } catch (aiError) {
      clearTimeout(timeoutId);
      if (aiError instanceof Error && aiError.name === 'AbortError') {
        console.error('AI request timed out');
        return new Response(
          JSON.stringify({ error: 'Request timed out. Please try with a smaller image.' }),
          { status: 504, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      throw aiError;
    }

  } catch (error) {
    console.error('Error in analyze-workflow-image:', error);
    console.error('Error stack:', error instanceof Error ? error.stack : 'No stack');
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        details: error instanceof Error ? error.stack : undefined
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
